### ISSUE TITLE
ADD FINAL CONTENT

### ISSUE THREAD

**Issue by jakewelchert** [jakewelchert/mtuck#8]
Need final copy for:
- Marshall's Vision
- About Marshall
- Social Share

**Comment by bhalligan** [comment]
"Tuck Message v9" is copy for Marshall's Vision page and "Tuck Bio v5" is About Marshall page

[031117 Tuck Message v9 Campaign Proofed.docx](https://github.com/jakewelchert/mtuck/files/835360/031117.Tuck.Message.v9.Campaign.Proofed.docx)
[031116 Tuck Bio v5 Campaign Proofed.docx](https://github.com/jakewelchert/mtuck/files/835361/031116.Tuck.Bio.v5.Campaign.Proofed.docx)

**Comment by bhalligan** [comment]
**Twitter share copy** 
I support @MarshallTuck for State Superintendent because he’s the best choice for students. Join me: [LINK] #TeamTuck

**Facebook share copy**
Headline: Marshall Tuck for State Superintendent
Description: The best choice for students.

**Email share text**
Subject: The candidate I support for State Superintendent
Body copy:
Hey,

I wanted to share this with you -- Marshall Tuck is running for California’s State Superintendent of Public Instruction, and I’m excited to support him. He’s got the experience and the vision to dramatically improve California’s public schools.

Check out his site for more information, and join me to get involved:

www.marshalltuck.com

**Comment by jakewelchert** [comment]
Resolved. Moving share stuff to other issue.
